# Generated by Django 4.2.7 on 2023-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex_2023', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellex2023',
            name='img',
            field=models.ImageField(default=1, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
